# REE and coal geodatabase
Unpacks the gdb which contains required element data and training features. GDB is structured by layers which are essentially individual datasets containing specific info about a coal field or chemical samples. These layers contain attributes / fields that are columns which hold the specific values.

### Import dependencies and identify layers of gdb ###

In [1]:
from pathlib import Path
import geopandas as gpd
import pandas as pd
import pyogrio

gdb_path = Path('ree-and-coal-open-geodatabase.gdb')
layers = pd.DataFrame(pyogrio.list_layers(gdb_path), columns=['name', 'geometry_type'])
print(f'{len(layers)} layers available')
display(layers)

388 layers available

c:\Users\antho\.virtualenvs\.venv\Lib\site-packages\pyogrio\core.py:169: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D MultiPolygon' is converted to 'MultiPolygon Z'
  return ogr_list_layers(get_vsi_path_or_buffer(path_or_buffer))

                                                  name geometry_type
0                                     REE0158_uscoal_p  MultiPolygon
1                                  REE0159_Coal_Fields  MultiPolygon
2                   REE0160_Coal_Field_Point_locations         Point
3                               REE0161_Coal_Provinces  MultiPolygon
4                         REE0163_NCRA_Assessed_Basins  MultiPolygon
..                                                 ...           ...
383                            REE0675_IL_Mines_All_Py  MultiPolygon
384                            REE0674_IL_Mines_All_Pt         Point
385                                REE0265_prb_Geology  MultiPolygon
386  REE0063_psmv_thk_South_Piceance_Coal_Field_Thi...  MultiPolygon
387                                REE0263_Drill_Holes         Point

[388 rows x 2 columns]

In [27]:
# Change the search text to find layers relevant to your analysis.
search_text = 'data'
pd.set_option("display.max_colwidth", None)
layers[layers['name'].str.contains(search_text, case=False, regex=False)]

,name,geometry_type
33,REE0435_z6iso_dp_Northeast_Texas_Coal_Zone_6_Northeast_Texas_Coal_Zone_6_Public_Data_Points,Point
34,REE0431_z5iso_dp_Northeast_Texas_Coal_Zone_5_Northeast_Texas_Coal_Zone_5_Public_Data_Points,Point
35,REE0427_z4iso_dp_Northeast_Texas_Coal_Zone_4_Northeast_Texas_Coal_Zone_4_Public_Data_Points,Point
36,REE0423_z3iso_dp_Northeast_Texas_Coal_Zone_3_Northeast_Texas_Coal_Zone_3_Public_Data_Points,Point
37,REE0404_lasab_dp_Louisiana_Sabine_Naborton_Coal_Zone_2_Louisiana_Sabine_Public_Data_Points,Point
38,REE0392_czm5_dp_Central_Texas_Central_Coal_Zone_5_Central_Texas_Central_Coal_Zone_5_Public_Data_Points,Point
39,REE0388_czm4_dp_Central_Texas_Central_Coal_Zone_4_Central_Texas_Central_Coal_Zone_4_Public_Data_Points,Point
40,REE0383_czl8_dp_Central_Texas_South_Coal_Zone_8_Central_Texas_South_Coal_Zone_8_Public_Data_Points,Point
41,REE0379_czl6_dp_Central_Texas_South_Coal_Zone_6_Central_Texas_South_Coal_Zone_6_Public_Data_Points,Point
42,REE0375_czl4_dp_Central_Texas_South_Coal_Zone_4_Central_Texas_South_Coal_Zone_4_Public_Data_Points,Point
43,REE0371_cz9_dp_Central_Texas_North_Coal_Zone_9_Central_Texas_North_Coal_Zone_9_Public_Data_Points,Point
44,REE0367_cz8_dp_Central_Texas_North_Coal_Zone_8_Central_Texas_North_Coal_Zone_8_Public_Data_Points,Point
45,REE0363_cz6_dp_Central_Texas_North_Coal_Zone_6_Central_Texas_North_Coal_Zone_6_Public_Data_Points,Point
46,REE0359_cz5_dp_Central_Texas_North_Coal_Zone_5_Central_Texas_North_Coal_Zone_5_Public_Data_Points,Point
65,REE0009_Trace_Elements_Data,Point
66,REE0008_Proximate_Ultimate_Data,Point
67,REE0007_Oxide_Data,Point
89,REE0459_Mountain_Peaks_in_Wyoming_24k_USGS_Names_Database,Point

## Rare earth element level data

In [44]:
layer_name = 'REE0009_Trace_Elements_Data'
element_data = gpd.read_file(gdb_path, layer=layer_name)
print(f'Loaded {len(element_data):,} features; CRS: {element_data.crs}')

Loaded 7,658 features; CRS: EPSG:4326

In [45]:
# pd.set_option("display.max_columns", None)
element_data

,Sample_ID,State,County,Latitude,Longitude,Province,Region,Field,District,Formation,Group_,Bed,Member,Coal_Zone,Depth__in_,Thickness__in_,System,Series_Epoch,Literature,Comments,Map,Collector,Mine_PowerPlant,Drill_Core_No,PointId,Submit_Date,Sample_Description,Estimated_Rank,Apparent_Rank,Analytical_Lab,Sample_Type,Analysis_Type,Values_Represent,Township,Range,Section_,Quarters,Tract,Location_Detail,Strat,OBJECTID_1,Sample_ID_1,GSAsh_Dry,GSAsh_Dry_Q,Si,Si_Q,Al,Al_Q,Ca,Ca_Q,Mg,Mg_Q,Na,Na_Q,K,K_Q,Fe,Fe_Q,Ti,Ti_Q,TS,TS_Q,Ag,Ag_Q,As,As_Q,Au,Au_Q,B,B_Q,Ba,Ba_Q,Be,Be_Q,Bi,Bi_Q,Br,Br_Q,Cd,Cd_Q,Ce,Ce_Q,Cl,Cl_Q,Co,Co_Q,Cr,Cr_Q,Cs,Cs_Q,Cu,Cu_Q,Dy,Dy_Q,Er,Er_Q,Eu,Eu_Q,F,F_Q,Ga,Ga_Q,Gd,Gd_Q,Ge,Ge_Q,Hf,Hf_Q,Hg,Hg_Q,Ho,Ho_Q,In_,In_Q,Ir,Ir_Q,La,La_Q,Li,Li_Q,Lu,Lu_Q,Mn,Mn_Q,Mo,Mo_Q,Nb,Nb_Q,Nd,Nd_Q,Ni,Ni_Q,Os,Os_Q,P,P_Q,Pb,Pb_Q,Pd,Pd_Q,Pr,Pr_Q,Pt,Pt_Q,Rb,Rb_Q,Re,Re_Q,Rh,Rh_Q,Ru,Ru_Q,Sb,Sb_Q,Sc,Sc_Q,Se,Se_Q,Sm,Sm_Q,Sn,Sn_Q,Sr,Sr_Q,Ta,Ta_Q,Tb,Tb_Q,Te,Te_Q,Th,Th_Q,Tl,Tl_Q,Tm,Tm_Q,U,U_Q,V,V_Q,W,W_Q,Y,Y_Q,Yb,Yb_Q,Zn,Zn_Q,Zr,Zr_Q,Strat_1,source_organization,dataset_name,hyperlink,dateupdated,source_ID,geometry
0,W214229,Alabama,BIBB,33.1847,-87.0422,EASTERN,SOUTHERN APPALACHIAN,CAHABA,NaN,POTTSVILLE,NaN,LOWER WADSWORTH,NaN,NaN,0.0,10.0,Pennsylvanian,Lower,NaN,NaN,HALFMILE SHOALS (7.5'),ALGS-BARWOOD H L,BURGESS,NaN,BHS-1,1981-07-17 00:00:00+00:00,BITUMINOUS COAL,BITUMINOUS,High volatile A bituminous,GT and USGS,Channel,As Received,Single sample,NaN,NaN,NaN,None,NaN,NaN,NaN,513.0,W214229,49.50,NaN,122000.0,NaN,57900.0,NaN,1440.0,NaN,5940.0,NaN,545.0,NaN,20300.0,NaN,44200.0,NaN,2530.0,NaN,0.638,"s,d",0.1140,NaN,203.00,NaN,5.00,L,45.10,NaN,644.0,NaN,1.880,NaN,5.00,L,1.01,NaN,0.1290,NaN,45.60,NaN,110.0,L,12.60,NaN,55.10,NaN,8.000,NaN,41.60,NaN,11.0,L,5.00,L,0.871,NaN,608.0,NaN,21.300,NaN,7.50,L,1.440,NaN,1.720,NaN,0.2730,NaN,3.40,L,3.40,L,7.50,L,24.30,NaN,45.10,NaN,0.2840,NaN,119.00,NaN,12.400,NaN,2.380,NaN,16.00,L,36.60,NaN,11.00,L,238.0,NaN,10.40,NaN,0.500,L,34.0,L,2.30,L,99.3,NaN,5.00,L,1.10,L,1.10,L,13.000,NaN,12.100,NaN,3.81,NaN,3.44,NaN,0.750,L,119.0,NaN,0.5470,NaN,0.638,NaN,NaN,B,6.890,NaN,2.30,L,2.30,L,2.43,NaN,84.20,NaN,1.110,NaN,7.92,NaN,2.030,NaN,79.20,NaN,28.20,NaN,NaN,USGS,COALQUAL,https://ncrdspublic.er.usgs.gov/coalqual/,2015,2,POINT (-87.04218 33.18469)
1,W223486,Alabama,BIBB,33.0800,-87.0619,EASTERN,SOUTHERN APPALACHIAN,CAHABA,NaN,POTTSVILLE,THOMPSON,THOMPSON,NaN,NaN,0.0,26.4,Pennsylvanian,Middle,NaN,NaN,WEST BLOCTON EAST (7.5'),ALGS-BARNETT R L,SURFACE MINE,NaN,BWBE-1,1983-12-12 00:00:00+00:00,BITUMINOUS COAL,BITUMINOUS,High volatile C bituminous,GT and USGS,Weathered Channel,As Received,Single sample,NaN,NaN,NaN,None,NaN,NaN,NaN,759.0,W223486,2.71,NaN,4610.0,NaN,3630.0,NaN,1230.0,NaN,461.0,NaN,59.6,NaN,412.0,NaN,2390.0,NaN,119.0,NaN,2.960,"s,d",0.0407,NaN,2.06,NaN,0.19,L,6.51,NaN,62.3,NaN,0.380,NaN,0.28,L,4.97,NaN,0.0152,NaN,6.15,NaN,146.0,NaN,2.84,NaN,3.75,NaN,0.271,NaN,5.69,NaN,0.6,L,0.13,L,0.178,NaN,41.7,NaN,0.976,NaN,0.87,L,1.110,NaN,0.126,NaN,0.1770,NaN,0.19,L,0.28,L,0.41,L,3.27,NaN,3.80,NaN,0.0396,NaN,4.34,NaN,2.980,NaN,0.325,NaN,4.34,NaN,6.51,NaN,0.41,L,13.6,NaN,1.25,NaN,0.028,L,2.8,L,0.06,L,6.3,L,0.28,L,0.06,L,0.06,L,0.792,NaN,0.971,NaN,1.04,NaN,0.71,NaN,0.130,L,35.2,NaN,0.0281,NaN,0.108,NaN,NaN,B,0.678,NaN,0.28,L,0.13,L,0.23,L,5.69,NaN,0.167,NaN,2.71,NaN,0.344,NaN,2.71,NaN,2.98,NaN,NaN,USGS,COALQUAL,https://ncrdspublic.er.usgs.gov/coalqual/,2015,2,POINT (-87.06189 33.08008)
2,W206495,Alabama,BLOUNT,34.2028,-86.4089,EASTERN,SOUTHERN APPALACHIAN,WARRIOR,NaN,POTTSVILLE,NaN,UPPER CLIFF NO 1,NaN,NaN,0.0,8.0,Pennsylvanian,Lower,NaN,NaN,BROOKSVILLE (7.5'),ALGS-HORSEY C,ENERGY ENTERPRISE,NaN,BBR-1,1979-04-27 00:00:00+00:00,BITUMINOUS COAL,BITUMINOUS,Medium volatile bituminous,USBM and USGS,Channel,NaN,Single sample,NaN,NaN,NaN,None,NaN,NaN,NaN,132.0,W206495,12.40,NaN,32300.0,NaN,16600.0,NaN,484.0,NaN,745.0,NaN,161.0,NaN,3180.0,NaN,5310.0,NaN,931.0,NaN,0.404,"s,d",0.0130,L,1.11,NaN,1.30,L,16.10,NaN,57.1,NaN,1.740,NaN,1.30,L,78.50,NaN,0.0484,NaN,21.20,NaN,1410.0,NaN,4.94,NaN,17.70,NaN,2.020,NaN,13.70,NaN,2.8,L,1.30,L,0.373,NaN,72.7,NaN,4.470,NaN,1.90,L,0.869,NaN,1.410,NaN,0.0110,L,0.85,L,0.85,L,1.90,L,11.10,NaN,13.70,NaN,0.1820,NaN,11.70,NaN,0.372,NaN,2.110,NaN,10.90,NaN,10.20,NaN,2.80,L,106.0,NaN,5.59,NaN,0.130,L,8.5,L,0.58,L,37.3,NaN,1.30,L,0.28,L,0.28,L,0.404,NaN,3.240,NaN,1.31,NaN,2.02,NaN,0.559,NaN,83.2,NaN,0.1410,NaN,0.293,NaN,NaN,B,3.230,NaN,0.58,L,0.58,L,1.39,NaN,21.10,NaN,1.010,NaN,6.58,NaN,1.010,NaN,14.90,NaN,19.90,NaN,NaN,USGS,COALQUAL,https://ncrdspublic.er.usgs.gov/coalqual/,2015,2,POINT (-86.40887 34.20288)
3,W233998,Alabama,BLOUNT,33.8778,-86.3725,EASTERN,SOUTHERN APPALACHIAN,WARRIOR,NaN,POTTSVILLE,NaN,CASKIE,NaN,NaN,0.0,31.8,Pennsylvanian,Middle,NaN,NaN,HYATT GAP (7.5'),ALGS,SURFACE MINE,NaN,BHG-1,1985-11-25 00:00:00+00:00,BITUMINOUS COAL,BITUMINOUS,High volatile A bituminous,GT and USGS,Channel,As Received,Single sample,NaN,NaN,NaN,None,NaN,NaN,NaN,876.0,W233998,14.70,NaN,23800.0,NaN,13900.0,NaN,1120.0,NaN,691.0,NaN,118.0,NaN,2980.0,NaN,38300.0,NaN,647.0,NaN,0.795,"s,d",0.0691,NaN,88.60,NaN,1.00,L,38.20,NaN,82.3,NaN,1.190,NaN,1.50,L,34.60,NaN,0.1060,NaN,12.50,NaN,1290.0,NaN,4.23,NaN,12.10,NaN,1.140,NaN,38.20,NaN,3.3,L,0.68,L,0.302,NaN,20.1,NaN,NaN,B,4.80,L,0.680,L,0.413,NaN,0.1610,NaN,1.00,L,1.50,L,2.30,L,9.13,NaN,25.00,NaN,0.0966,NaN,26.50,NaN,NaN,B,1.340,NaN,12.50,NaN,22.00,NaN,2.30,L,147.0,NaN,8.82,NaN,0.150,L,15.0,L,0.33,L,41.0,L,1.50,L,0.33,L,0.33,L,6.030,NaN,2.720,NaN,2.41,NaN,1.87,NaN,NaN,B,146.0,NaN,0.1490,NaN,0.180,NaN,NaN,B,1.930,NaN,1.50,L,0.68,L,1.21,NaN,23.50,NaN,0.453,NaN,6.91,NaN,0.685,NaN,27.90,NaN,22.00,NaN,NaN,USGS,COALQUAL,https://ncrdspublic.er.usgs.gov/coalqual/,2015,2,POINT (-86.3725 33.87793)
4,W233999,Alabama,BLOUNT,33.9483,-86.7047,EASTERN,SOUTHERN APPALACHIAN,WARRIOR,NaN,POTTSVILLE,NaN,TIDEMORE,NaN,NaN,0.0,30.0,Pennsylvanian,Middle,NaN,NaN,NECTAR (7.5'),ALGS,SURFACE MINE,NaN,BNT-1,1985-11-25 00:00:00+00:00,BITUMINOUS COAL,BITUMINOUS,Medium volatile bituminous,GT and USGS,Channel,As Received,Single sample,NaN,NaN,NaN,None,NaN,NaN,NaN,877.0,W233999,16.60,NaN,42000.0,NaN,21400.0,NaN,549.0,NaN,1050.0,NaN,250.0,NaN,4160.0,NaN,12300.0,NaN,1150.0,NaN,0.211,"s,d",0.0549,NaN,69.60,NaN,1.20,L,21.60,NaN,73.3,NaN,2.000,NaN,1.70,L,19.60,NaN,0.0966,NaN,14.50,NaN,682.0,NaN,8.45,NaN,13.00,NaN,1.560,NaN,30.00,NaN,3.7,L,0.77,L,0.333,NaN,21.0,L,5.330,NaN,5.40,L,1.660,NaN,0.602,NaN,0.0051,L,1.20,L,1.70,L,2.50,L,15.30,NaN,43.30,NaN,0.1290,NaN,26.60,NaN,2.160,NaN,2.500,NaN,15.70,NaN,26.60,NaN,2.50,L,49.9,NaN,7.99,NaN,0.170,L,17.0,L,0.37,L,41.0,L,1.70,L,0.37,L,0.37,L,1.520,NaN,2.820,NaN,1.32,NaN,2.85,NaN,2.000,NaN,49.9,NaN,0.2290,NaN,0.216,NaN,NaN,B,2.090,NaN,1.70,L,0.77,L,1.15,NaN,25.00,NaN,1.020,NaN,7.16,NaN,1.010,NaN,25.00,NaN,25.00,NaN,NaN,USGS,COALQUAL,https://ncrdspublic.er.usgs.gov/coalqual/,2015,2,POINT (-86.70471 33.9483)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7653,D210404,Wyoming,UINTA,41.5367,-110.5758,ROCKY MOUNTAIN,HAMS FORK,KEMMERER,KENDALL,FRONTIER,NaN,UNNAMED,NaN,NaN,2734.8,28.8,Cretaceous,Upper,NaN,NaN,CUMBERLAND GAP (7.5'),USGS-MGONIGLE J W,NO DATA ENTERED,CG-3,CG-3D,1979-01-12 00:00:00+00:00,BITUMINOUS COAL,BITUMINOUS,High volatile B bituminous,USBM and USGS,Drill Core,As Received,Single sample,18N,116W,18,None,NaN,NaN,D210404-00-S2,7311.0,D210404,15.70,NaN,39200.0,NaN,18800.0,NaN,8010.0,NaN,440.0,NaN,675.0,NaN,534.0,NaN,3610.0,NaN,1260.0,NaN,NaN,B,NaN,B,1.17,NaN,NaN,B,31.40,NaN,31.4,NaN,1.570,NaN,NaN,B,NaN,B,0.1570,NaN,79.00,L,110.0,L,4.27,NaN,6.61,NaN,NaN,B,12.40,NaN,NaN,B,NaN,B,NaN,B,46.5,NaN,4.710,NaN,NaN,B,4.710,NaN,NaN,B,0.0310,NaN,NaN,B,NaN,B,NaN,B,16.00,L,28.10,NaN,NaN,B,138.00,NaN,4.710,NaN,3.140,NaN,NaN,B,4.71,NaN,NaN,B,63.0,L,6.91,NaN,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,3.250,NaN,2.350,NaN,1.69,NaN,NaN,B,NaN,B,23.5,NaN,NaN,B,NaN,B,NaN,B,3.880,NaN,NaN,B,NaN,B,2.66,NaN,23.50,NaN,NaN,B,11.00,NaN,0.785,NaN,16.80,NaN,47.10,NaN,D210404-00-S2,USGS,COALQUAL,https://ncrdspublic.er.usgs.gov/coalqual/,2015,2,POINT (-110.57581 41.53668)
7654,D210405,Wyoming,UINTA,41.5367,-110.5758,ROCKY MOUNTAIN,HAMS FORK,KEMMERER,KENDALL,FRONTIER,NaN,UNNAMED,NaN,NaN,4034.4,30.0,Cretaceous,Upper,NaN,NaN,CUMBERLAND GAP (7.5'),USGS-MGONIGLE J W,NO DATA ENTERED,CG-3,CG-3E,1979-01-12 00:00:00+00:00,BITUMINOUS COAL,BITUMINOUS,High volatile B bituminous,USBM and USGS,Drill Core,As Received,Single sample,18N,116W,18,None,NaN,NaN,D210405-00-S3,7312.0,D210405,8.68,NaN,20800.0,NaN,12100.0,NaN,3210.0,NaN,321.0,NaN,469.0,NaN,304.0,NaN,3560.0,NaN,581.0,NaN,NaN,B,NaN,B,1.11,NaN,NaN,B,17.40,NaN,26.0,NaN,0.434,NaN,NaN,B,NaN,B,0.0868,NaN,44.00,L,110.0,L,1.51,NaN,4.36,NaN,NaN,B,7.03,NaN,NaN,B,NaN,B,NaN,B,41.3,NaN,2.600,NaN,NaN,B,2.600,NaN,NaN,B,0.0826,NaN,NaN,B,NaN,B,NaN,B,8.70,L,16.70,NaN,NaN,B,61.30,NaN,0.610,L,1.740,NaN,NaN,B,1.30,NaN,NaN,B,35.0,L,2.20,L,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,1.110,NaN,1.300,NaN,1.37,NaN,NaN,B,NaN,B,26.0,NaN,NaN,B,NaN,B,NaN,B,0.110,L,NaN,B,NaN,B,2.13,NaN,8.68,NaN,NaN,B,6.07,NaN,0.607,NaN,16.20,NaN,26.00,NaN,D210405-00-S3,USGS,COALQUAL,https://ncrdspublic.er.usgs.gov/coalqual/,2015,2,POINT (-110.57581 41.53668)
7655,D210406,Wyoming,UINTA,41.5367,-110.5697,ROCKY MOUNTAIN,HAMS FORK,KEMMERER,KENDALL,FRONTIER,NaN,UNNAMED,NaN,NaN,6886.8,25.2,Cretaceous,Upper,NaN,NaN,CUMBERLAND GAP (7.5'),USGS-MGONIGLE J W,NO DATA ENTERED,CG-3,CG-3F,1979-01-12 00:00:00+00:00,BITUMINOUS COAL,BITUMINOUS,High volatile B bituminous,USBM and USGS,Drill Core,As Received,Single sample,18N,116W,18,None,NaN,NaN,D210406-00-S3,7313.0,D210406,14.10,NaN,50600.0,NaN,8580.0,NaN,1410.0,NaN,661.0,NaN,928.0,NaN,1350.0,NaN,3090.0,NaN,422.0,NaN,NaN,B,NaN,B,8.34,NaN,NaN,B,21.10,NaN,42.2,NaN,0.422,NaN,NaN,B,NaN,B,0.1410,NaN,NaN,B,103.0,NaN,1.81,NaN,4.09,NaN,NaN,B,6.33,NaN,NaN,B,NaN,B,NaN,B,134.0,NaN,2.810,NaN,NaN,B,2.810,NaN,NaN,B,0.0414,NaN,NaN,B,NaN,B,NaN,B,NaN,B,6.89,NaN,NaN,B,29.90,NaN,0.990,L,2.900,L,NaN,B,2.11,NaN,NaN,B,57.0,L,3.60,L,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,0.972,NaN,1.410,NaN,1.24,NaN,NaN,B,NaN,B,21.1,NaN,NaN,B,NaN,B,NaN,B,2.240,NaN,NaN,B,NaN,B,1.87,NaN,9.84,NaN,NaN,B,7.03,NaN,0.703,NaN,14.20,NaN,21.10,NaN,D210406-00-S3,USGS,COALQUAL,https://ncrdspublic.er.usgs.gov/coalqual/,2015,2,POINT (-110.5697 41.53668)
7656,DA2210401,Wyoming,UINTA,41.5367,-110.5758,ROCKY MOUNTAIN,HAMS FORK,KEMMERER,KENDALL,FRONTIER,NaN,UNNAMED,NaN,NaN,7675.2,52.8,Cretaceous,Upper,NaN,NaN,CUMBERLAND GAP (7.5'),NaN,NO DATA ENTERED,CG-2,D210401-2,NaT,BITUMINOUS COAL,BITUMINOUS,High volatile B bituminous,NaN,Drill Core,NaN,Single bed combined,18N,116W,18,None,NaN,NaN,D210401-00A:01-S4,7524.0,DA2210401,18.30,a,49400.0,a,22000.0,a,5670.0,a,677.0,a,1200.0,a,778.0,a,4850.0,a,1250.0,a,NaN,B,NaN,B,1.44,a,NaN,B,36.60,a,54.9,a,0.915,a,NaN,B,NaN,B,0.4590,a,NaN,B,110.0,"L,a",3.42,a,7.86,a,NaN,B,13.10,a,NaN,B,NaN,B,NaN,B,49.1,a,5.490,a,NaN,B,5.490,a,NaN,B,0.0258,a,NaN,B,NaN,B,NaN,B,19.00,"L,a",25.70,a,NaN,B,82.60,a,1.550,a,3.660,a,NaN,B,5.49,a,NaN,B,74.0,"L,a",6.13,a,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,2.900,a,2.750,a,1.82,a,NaN,B,NaN,B,27.5,a,NaN,B,NaN,B,NaN,B,4.160,a,NaN,B,NaN,B,3.47,a,18.30,a,NaN,B,9.15,a,0.731,a,10.10,a,54.90,a,D210401-00A:01-S4,USGS,COALQUAL,https://ncrdspublic.er.usgs.gov/coalqual/,2015,2,POINT (-110.57581 41.53668)
7657,DA2210396,Wyoming,UINTA,41.4783,-110.6147,ROCKY MOUNTAIN,HAMS FORK,KEMMERER,KENDALL,FRONTIER,NaN,UNNAMED,NaN,NaN,4081.2,55.2,Cretaceous,Upper,NaN,NaN,BRIDGER (7.5'),NaN,NO DATA ENTERED,B-1,D210396-7,NaT,BITUMINOUS COAL,BITUMINOUS,High volatile C bituminous,NaN,Drill Core,NaN,Single bed combined,17N,117W,2,None,NaN,NaN,"D210396-00A:01,02-S2",7523.0,DA2210396,10.90,a,26600.0,a,4710.0,a,8450.0,a,918.0,a,567.0,a,303.0,a,7090.0,a,267.0,a,NaN,B,NaN,B,1.31,a,NaN,B,75.90,a,75.9,a,0.392,a,NaN,B,NaN,B,0.1100,"L,a",NaN,B,110.0,"L,a",1.44,a,3.52,a,NaN,B,4.32,a,NaN,B,NaN,B,NaN,B,39.2,a,1.790,a,NaN,B,NaN,B,NaN,B,0.1130,a,NaN,B,NaN,B,NaN,B,NaN,B,3.79,a,NaN,B,67.30,a,1.250,a,2.170,a,NaN,B,1.63,a,NaN,B,44.0,"L,a",3.02,a,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,NaN,B,0.220,a,2.130,a,0.36,"L,a",NaN,B,NaN,B,75.9,a,NaN,B,NaN,B,NaN,B,1.260,a,NaN,B,NaN,B,1.06,a,10.30,a,NaN,B,4.59,a,0.459,a,6.14,a,17.90,a,"D210396-00A:01,02-S2",USGS,COALQUAL,https://ncrdspublic.er.usgs.gov/coalqual/,2015,2,POINT (-110.61469 41.47827)

In [46]:
counties = element_data["State"]
# pd.set_option("display.max_columns", None)
# pd.set_option("display.width", None)  
counties.describe()

count         7658
unique          36
top       Kentucky
freq          1006
Name: State, dtype: object

## Feature Level Data